import Kernel.Augmented.SimplexObstruction
import Kernel.Augmented.FromTwoCategory
import Kernel.Augmented.FromCat
import Kernel.Augmented.Examples
import Kernel.Augmented.AlgebraExamples
import Kernel.Augmented.SubstitutionExamples
import Kernel.Augmented.FromTwoCategoryAlgebra
import Kernel.Augmented.TwoCategoryNerve
import Kernel.Augmented.FreeCellUniversal
import Kernel.Augmented.TermSupport
import Kernel.Augmented.FreeGeneratingUniversal
import Kernel.Augmented.GeneratingCategory
import Kernel.Augmented.NerveSquare
import Kernel.Augmented.GeneratingComparisonIdentities
import Kernel.Augmented.GeneratingComparisonSubstitution
import Kernel.Augmented.GeneratingVerticalComparison
import Kernel.Augmented.GeneratingCellSubstitution
import Kernel.Augmented.ArityNerveComparison
import Kernel.Augmented.GeneratingFiniteExactness
/-! Augmented incidence and its checked prerequisites (D-KR-18, AT-FD-7). -/
