import Kernel.Augmented.CellTerms
import Kernel.Augmented.Algebra

/-! The congruence generated by exactly the five augmented algebra equation families.
Cites: D-KR-15, D-KR-18, D-TL-21, AT-FD-7.
-/

open CategoryTheory
namespace Kernel.Augmented.CellTerm
universe u v h c
variable {C : Type u} [Category.{v} C] {H : C → C → Type h}

inductive Related (G : CellGraph.{u,v,h,c} C H) :
    {b : CellBoundary C H} → CellTerm G b → CellTerm G b → Prop
  | refl {b} (t : CellTerm G b) : Related G t t
  | symm {b} {s t : CellTerm G b} : Related G s t → Related G t s
  | trans {b} {r s t : CellTerm G b} : Related G r s → Related G s t → Related G r t
  | operation (o : CellOperation C H) (x y : (p : o.Position) → CellTerm G (o.input p))
      (h : ∀ p, Related G (x p) (y p)) : Related G (.operation o x) (.operation o y)
  | verticalIdentity_stack {a b d : C} (f : a ⟶ b) (g : b ⟶ d) :
      Related G ((operations G).verticalStack ((operations G).verticalIdentity f)
        ((operations G).verticalIdentity g)) ((operations G).verticalIdentity (f ≫ g))
  | leftUnit {f g : Side C} {b : Boundary H f g} (φ : (graph G).Cell b) :
      Related G (CellGraph.transport (Operations.leftUnit_boundary φ)
        ((operations G).leftUnitComposite φ)) φ
  | rightUnit {f g : Side C} {b : Boundary H f g} (φ : (graph G).Cell b) :
      Related G (CellGraph.transport ((operations G).rightUnit_boundary b)
        ((operations G).rightUnitComposite φ)) φ
  | insertion {f g k : Side C} (p : (graph G).Row f g) (q : (graph G).Row g k)
      (hn : 0 < (p.comp q).length) {a b : C} (h : f.target ⟶ a) (l : k.target ⟶ b)
      (L : ShortPath H a b)
      (ψ : (graph G).Cell (CellGraph.Row.outerBoundary ⟨p.comp q, hn⟩ h l L)) :
      Related G (CellGraph.transport ((operations G).inserted_boundary p q hn h l L)
        ((operations G).insertedComposite p q hn h l L ψ))
        ((operations G).substitute ⟨p.comp q, hn⟩ h l L ψ)
  | assoc {s t : Nested.Side C} (r : Nested.NonemptyRow (graph G) s t)
      {a b : C} (p : s.bottom ⟶ a) (q : t.bottom ⟶ b) (L : ShortPath H a b)
      (χ : (graph G).Cell (CellGraph.Row.outerBoundary r.outer p q L)) :
      Related G (CellGraph.transport ((operations G).assoc_boundary r p q L)
        ((operations G).assocLeft r p q L χ)) ((operations G).assocRight r p q L χ)

def setoid (G : CellGraph.{u,v,h,c} C H) (b : CellBoundary C H) : Setoid (CellTerm G b) where
  r := Related G
  iseqv := ⟨Related.refl, Related.symm, Related.trans⟩

end Kernel.Augmented.CellTerm
